
Class Справочник.Регионы {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 +{static} Наименование
	 +{static} Код
}
Class Справочник.Банки {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 +{static} Наименование
	 +{static} Код
}
Class Справочник.Склады {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 +{static} Наименование
	 +{static} Код
	 #{static} НеИспользовать
}
Class Справочник.ВидыЦен {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 +{static} Наименование
	 +{static} Код
}
Class Справочник.ВходящиеПисьма {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 +{static} Наименование
	 ~{static} Дата
	 +{static} Отправитель
	 +{static} Текст
	 -{static} ВидСодержимого
	 +{static} Идентификатор
	 +{static} ПочтовыйЯщик
}
Class Справочник.ЗначенияХарактеристик {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 -{static} Владелец
	 +{static} Наименование
	 +{static} Код
}
Class Справочник.Контрагенты {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 #{static} ЭтоГруппа
	 -{static} Родитель
	 +{static} Наименование
	 +{static} Код
	 -{static} Регион
	 +{static} Индекс
	 +{static} Страна
	 +{static} Город
	 +{static} Улица
	 +{static} Дом
	 +{static} Телефон
	 +{static} ЭлектроннаяПочта
	 +{static} Факс
	 +{static} ВебСайт
	 -{static} ВидЦен
	 +{static} ДополнительнаяИнформация
	 +{static} КонтактноеЛицо
	 *{static} Широта
	 *{static} Долгота
}
Class Справочник.Товары {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 #{static} ЭтоГруппа
	 -{static} Родитель
	 +{static} Наименование
	 +{static} Код
	 +{static} Артикул
	 -{static} Поставщик
	 -{static} ФайлКартинки
	 -{static} Вид
	 +{static} Штрихкод
	 +{static} Описание
	 *{static} ВТ_Вес
}
Class Справочник.МобильныеУстройства {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 -{static} Владелец
	 +{static} Наименование
	 +{static} Код
	 {static} ИдентификаторПодписчикаДоставляемыхУведомлений
	 {static} Подписчик
}
Class Справочник.НастройкиТорговогоОборудования {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 +{static} Наименование
	 +{static} Код
	 *{static} БитДанных
	 *{static} Скорость
	 +{static} Порт
}
Class Справочник.ХранимыеФайлы {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 {static} Владелец
	 +{static} Наименование
	 +{static} Код
	 {static} ДанныеФайла
	 +{static} ИмяФайла
	 {static} Подпись
	 #{static} Подписан
	 #{static} Зашифрован
	 #{static} ДляОписания
}
Class Справочник.Валюты {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 +{static} Наименование
	 +{static} Код
	 +{static} НаименованиеОсновнойВалюты
	 +{static} НаименованиеРазменнойВалюты
}
Class Справочник.ПочтовыеВложения {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 -{static} Владелец
	 +{static} Наименование
	 +{static} Код
	 {static} Данные
}
Class Справочник.РасчетныеСчета {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 -{static} Владелец
	 +{static} Наименование
	 +{static} Код
	 +{static} Номер
	 -{static} Банк
}
Class Справочник.РасчетныеСчетаКонтрагентов {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 -{static} Владелец
	 +{static} Наименование
	 +{static} Код
	 +{static} Номер
	 -{static} Банк
}
Class Справочник.Организации {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 +{static} Наименование
	 +{static} Код
	 #{static} ВалютныйУчет
}
Class Справочник.Пользователи {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 +{static} Наименование
	 +{static} Код
	 {static} ИдентификаторПользователяИБ
}
Class Справочник.ИсходящиеПисьма {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 +{static} Наименование
	 ~{static} Дата
	 +{static} Получатель
	 {static} Содержимое
	 +{static} Текст
	 -{static} Контрагент
	---Получатели---
	 +ЭлектроннаяПочта
}
Class Справочник.ХранилищеВариантовОтчетов {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 +{static} Наименование
	 +{static} Код
	 {static} ВариантОтчета
	 +{static} КлючОбъекта
}
Class Справочник.Встречи {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 -{static} Владелец
	 +{static} Наименование
	 +{static} Код
	 ~{static} Начало
	 ~{static} Окончание
	 +{static} Описание
}
Class Справочник.ИсходящиеСообщенияRMQ {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 +{static} Код
	 +{static} Сообщение
	 #{static} КОтправке
	 +{static} ТочкаОбмена
	 +{static} ИмяОчереди
	 +{static} КлючМаршрутизации
}
Class Справочник.ИменаОчередейRMQ {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 +{static} Наименование
	 +{static} Код
}
Abstract Документ.Заказ {
	 #{static} Проведен
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 ~{static} Дата
	 +{static} Номер
	 -{static} Покупатель
	 -{static} Склад
	 -{static} Валюта
	 -{static} ВидЦен
	 -{static} Организация
	 -{static} СостояниеЗаказа
	 -{static} Автор
	 *{static} Сумма
	---Товары---
	 -Товар
	 *Цена
	 *Количество
	 *Сумма
}
Abstract Документ.ОперацияПоУчетуТоваров {
	 #{static} Проведен
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 ~{static} Дата
	 +{static} Номер
	 +{static} СодержаниеОперации
	 -{static} Организация
}
Abstract Документ.Оплата {
	 #{static} Проведен
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 ~{static} Дата
	 +{static} Номер
	 -{static} Поставщик
	 -{static} РасчетныйСчетПоставщика
	 -{static} РасчетныйСчет
	 -{static} Валюта
	 *{static} Сумма
	 -{static} Организация
}
Abstract Документ.ПоступлениеДенег {
	 #{static} Проведен
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 ~{static} Дата
	 +{static} Номер
	 -{static} Покупатель
	 -{static} РасчетныйСчетПокупателя
	 -{static} РасчетныйСчет
	 -{static} Валюта
	 *{static} Сумма
	 -{static} Организация
}
Abstract Документ.ПриходТовара {
	 #{static} Проведен
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 ~{static} Дата
	 +{static} Номер
	 -{static} Поставщик
	 -{static} Склад
	 -{static} Валюта
	 -{static} Организация
	---Товары---
	 -Товар
	 *Цена
	 *Количество
	 *Сумма
}
Abstract Документ.РасходТовара {
	 #{static} Проведен
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 ~{static} Дата
	 +{static} Номер
	 -{static} Покупатель
	 -{static} Склад
	 -{static} Валюта
	 -{static} ВидЦен
	 +{static} ОбоснованиеОтгрузки
	 -{static} Организация
	 +{static} ПодарочныйСертификат
	 *{static} СуммаПодарочногоСертификата
	 #{static} РезультатПолучен
	 *{static} СуммаСписанияСертификата
	---Товары---
	 -Товар
	 *Цена
	 *Количество
	 *Сумма
	 *СуммаСертификата
}
Abstract Документ.РегистрацияПодарочныхСертификатов {
	 #{static} Проведен
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 ~{static} Дата
	 +{static} Номер
	---ТЧПодрочныеСертификаты---
	 +НомерСертификата
	 *СуммаСертификата
}
Protocol Перечисление.ВидыТоваров {
	 *{static} Порядок
	 -{static} Ссылка
	 {static} Товар
	 {static} Услуга
}
Protocol Перечисление.ВидНастройкиАутентификацииSMTP {
	 *{static} Порядок
	 -{static} Ссылка
	 {static} Нет
	 {static} ПолучатьССервера
	 {static} РучнаяНастройка
}
Protocol Перечисление.ВидСодержимогоВходящегоПисьма {
	 *{static} Порядок
	 -{static} Ссылка
	 {static} Текст
	 {static} HTML
}
Protocol Перечисление.PushУведомления {
	 *{static} Порядок
	 -{static} Ссылка
	 {static} НеИспользовать
	 {static} ОтправлятьНепосредственно
	 {static} ИспользоватьВспомогательныйСервис
}
Protocol Перечисление.ВидыМобильныхОтчетов {
	 *{static} Порядок
	 -{static} Ссылка
	 {static} ОстаткиТоваровНаСкладах
}
Protocol Перечисление.СостоянияЗаказов {
	 *{static} Порядок
	 -{static} Ссылка
	 {static} Открыт
	 {static} ВРаботе
	 {static} Выполнен
	 {static} Закрыт
}
Protocol Перечисление.НазначениеХарактеристик {
	 *{static} Порядок
	 -{static} Ссылка
	 {static} Товары
	 {static} Контрагенты
}
Protocol Перечисление.ИспользоватьПровайдерГеопозиционирования {
	 *{static} Порядок
	 -{static} Ссылка
	 {static} СамыйТочныйПровайдер
	 {static} СамыйЭкономичныйПровайдер
	 {static} ВыбиратьИзСписка
}
Protocol Отчет.ВзаимосвязьПродажТоваров {
}
Protocol Отчет.ДашбордПродажи {
}
Protocol Отчет.ДинамикаПродаж {
}
Protocol Отчет.ДокументыОплата {
}
Protocol Отчет.ОстаткиТоваровНаСкладах {
}
Protocol Отчет.ОтчетПоВзаиморасчетам {
}
Protocol Отчет.ПрайсЛист {
}
Protocol Отчет.АнализЗаказов {
}
Protocol Отчет.ОстаткиТоваровНаСкладахМобильный {
}
Interface Обработка.АдминистративныйСервис {
}
Interface Обработка.ДемонстрацияВозможностейДиаграмм {
}
Interface Обработка.ЖурналРегистрации {
}
Interface Обработка.НастройкиПользователя {
}
Interface Обработка.ПроведениеДокументов {
	 {static} СписокДокументов
	 {static} ВыбранныеДокументы
	 +{static} Проводить
}
Interface Обработка.Путеводитель {
}
Interface Обработка.РедактированиеЦен {
}
Interface Обработка.СписокАктивныхПользователей {
}
Interface Обработка.УдалениеПомеченныхОбъектов {
}
Interface Обработка.УправлениеАгрегатамиПродаж {
}
Interface Обработка.УправлениеНастройкамиФорм {
}
Interface Обработка.УправлениеПолнотекстовымПоиском {
}
Interface Обработка.УправлениеСистемойВзаимодействия {
}
Interface Обработка.ЭлектроннаяПочта {
}
Struct ПланВидовХарактеристик.ВидыХарактеристик {
	 +{static} ИмяПредопределенныхДанных
	 {static} ТипЗначения
	 +{static} Наименование
	 +{static} Код
	 #{static} Предопределенный
	 #{static} ПометкаУдаления
	 -{static} Ссылка
	 -{static} Назначение
	 #{static} Множественная
}
Entity РегистрСведений.КурсыВалют {
	 ~{static} Период
---Измерения---
	 -Валюта
---Ресурсы---
	 *Курс
}
Entity РегистрСведений.ЦеныТоваров {
	 ~{static} Период
---Измерения---
	 -Товар
	 -ВидЦен
---Ресурсы---
	 *Цена
}
Entity РегистрСведений.СостояниеВходящихПисем {
---Измерения---
	 -Письмо
---Ресурсы---
	 #Прочитано
}
Entity РегистрСведений.СостояниеИсходящихПисем {
---Измерения---
	 -Письмо
---Ресурсы---
	 #Отправлено
}
Entity РегистрСведений.Характеристики {
---Измерения---
	 Объект
	 -ВидХарактеристики
	 *Номер
---Ресурсы---
	 Значение
}
Entity РегистрСведений.МобильныеОтчеты {
---Измерения---
	 -Вид
	 +Получатель
---Ресурсы---
	 Содержимое
	 +Настройки
	 #ОбновлятьПриОбмене
	 +ИнформацияРасшифровки
	 *ХешСумма
}
Enum РегистрНакопления.Взаиморасчеты {
	 {static} ВидДвижения
	 #{static} Активность
	 *{static} НомерСтроки
	 {static} Регистратор
	 ~{static} Период
}
Enum РегистрНакопления.Продажи {
	 #{static} Активность
	 *{static} НомерСтроки
	 -{static} Регистратор
	 ~{static} Период
}
Enum РегистрНакопления.ТоварныеЗапасы {
	 {static} ВидДвижения
	 #{static} Активность
	 *{static} НомерСтроки
	 {static} Регистратор
	 ~{static} Период
}
Справочник.Контрагенты --> Справочник.ХранимыеФайлы::Владелец
Справочник.Товары --> Справочник.ХранимыеФайлы::Владелец
Справочник.Товары --> Документ.Заказ::Товар
Справочник.Товары --> Документ.ПриходТовара::Товар
Справочник.Товары --> Документ.РасходТовара::Товар
Справочник.Валюты --> РегистрСведений.КурсыВалют::Валюта
Справочник.Товары --> РегистрСведений.ЦеныТоваров::Товар
Справочник.ВидыЦен --> РегистрСведений.ЦеныТоваров::ВидЦен
Справочник.ВходящиеПисьма --> РегистрСведений.СостояниеВходящихПисем::Письмо
Справочник.ИсходящиеПисьма --> РегистрСведений.СостояниеИсходящихПисем::Письмо
Справочник.Контрагенты --> РегистрСведений.Характеристики::Объект
Справочник.Товары --> РегистрСведений.Характеристики::Объект
ПланВидовХарактеристик.ВидыХарактеристик --> РегистрСведений.Характеристики::ВидХарактеристики
Справочник.ЗначенияХарактеристик --> РегистрСведений.Характеристики::Значение
Справочник.Склады --> РегистрСведений.Характеристики::Значение
Справочник.ВидыЦен --> РегистрСведений.Характеристики::Значение
Справочник.РасчетныеСчета --> РегистрСведений.Характеристики::Значение
Справочник.Банки --> РегистрСведений.Характеристики::Значение
Справочник.Контрагенты --> РегистрСведений.Характеристики::Значение
Справочник.Регионы --> РегистрСведений.Характеристики::Значение
Справочник.Товары --> РегистрСведений.Характеристики::Значение
Справочник.Организации --> РегистрСведений.Характеристики::Значение
Справочник.РасчетныеСчетаКонтрагентов --> РегистрСведений.Характеристики::Значение
Справочник.Валюты --> РегистрСведений.Характеристики::Значение
Перечисление.ВидыМобильныхОтчетов --> РегистрСведений.МобильныеОтчеты::Вид
Документ.ПриходТовара --> РегистрНакопления.Взаиморасчеты::Регистратор
Документ.РасходТовара --> РегистрНакопления.Взаиморасчеты::Регистратор
Документ.Оплата --> РегистрНакопления.Взаиморасчеты::Регистратор
Документ.ПоступлениеДенег --> РегистрНакопления.Взаиморасчеты::Регистратор
Документ.ПриходТовара --> РегистрНакопления.ТоварныеЗапасы::Регистратор
Документ.РасходТовара --> РегистрНакопления.ТоварныеЗапасы::Регистратор
Документ.ОперацияПоУчетуТоваров --> РегистрНакопления.ТоварныеЗапасы::Регистратор
remove @unlinked