
Class Справочник.ИменаОчередейRMQ {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 +{static} Наименование
	 +{static} Код
}
Abstract Документ.РегистрацияПодарочныхСертификатов {
	 #{static} Проведен
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 ~{static} Дата
	 +{static} Номер
	---ТЧПодрочныеСертификаты---
	 +НомерСертификата
	 *СуммаСертификата
}
Abstract Документ.СписаниеСуммПодарочныхСертификатов {
	 #{static} Проведен
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 ~{static} Дата
	 +{static} Номер
	 +{static} Сертификат
	 *{static} СуммаСписания
}
Enum РегистрНакопления.ОстаткиПодарочныхСертификатов {
	 {static} ВидДвижения
	 #{static} Активность
	 *{static} НомерСтроки
	 {static} Регистратор
	 ~{static} Период
}
Документ.РегистрацияПодарочныхСертификатов --> РегистрНакопления.ОстаткиПодарочныхСертификатов::Регистратор
Документ.СписаниеСуммПодарочныхСертификатов --> РегистрНакопления.ОстаткиПодарочныхСертификатов::Регистратор